# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'


- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '5.0.x'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/bin/Benchmarkdll
    artifactName: Benchmarkdll
# Azure file copy
# Copy files to Azure Blob Storage or virtual machines
# Azure file copy
# Copy files to Azure Blob Storage or virtual machines
- task: AzureFileCopy@4
  inputs:
    sourcePath: $(System.DefaultWorkingDirectory)/bin/Benchmarkdll
    azureSubscription: 8639aadc-9332-43df-ac5a-5e75d42cb6c0
    destination: azureVMs
    storage: c:\drake
    #containerName: # Required when destination == AzureBlob
    #blobPrefix: # Optional
    resourceGroup: Devops
    resourceFilteringMethod: 'machineNames' 
    machineNames: abhinavvm
    vmsAdminUserName: mcaabhinav
    vmsAdminPassword: sqlserver@k21A
    #targetPath: # Required when destination == AzureVMs
    #additionalArgumentsForBlobCopy: # Optional
    #additionalArgumentsForVMCopy: # Optional
    #enableCopyPrerequisites: false # Optional
    #copyFilesInParallel: true # Optional
    cleanTargetBeforeCopy: true # Optional
    #skipCACheck: true # Optional
    #sasTokenTimeOutInMinutes: # Optional